# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: 
        - gcc
        - clang
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get repository ppa:llvm-toolchain-trusty main -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.7 lldb-3.7;fi
  - ${CXX} --version
  - sudo apt-get install -qq bc jq samtools
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - python ./configure.py
  - source ./source_me.sh
install: make get-deps
script: make && make test
