# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: 
        - gcc
        - clang
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - gcc --version && g++ --version
  - sudo apt-get install -qq bc jq samtools
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - python ./configure.py
  - source ./source_me.sh
install: make get-deps
script: make && make test
